config/routes.rb
Diary::Application.routes.draw do
  get "welcome/index"
resources "entries"

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :contents, :date, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
def index
	@entries = Entry.all
end
def show
		@entry = Entry.find(params["id"])

		end
		def create
			#entry_params = params["entry"]
			entry_params = params["entry"].permit("title", "contents")
			entry = Entry.create(entry_params)
			redirect_to(entry_path(entry))
		end
		def edit
			@entry = Entry.find(params["id"])
		end

end
# NEED enough ENDS -- ONE TO END EACH DEFINITION "DEF" AND ALSO TO END THE CLASS "CLASS"

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@websites = [
  		["http://railsgirls.com", "Rails Girls"],
  		["https://en.wikibooks.org/wiki/Ruby_Programming", "Wikibooks"],
  		["http://guides.rubyonrails.org", "Ruby on Rails Guides"],
  	]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/index.html.erb
<% for entry in @entries %>
<h2><%= link_to(entry.title, entry_path(entry)) %></h2>
<p><%= entry.date%></p>
<p><%= entry.contents%></p>
<%= link_to("New entry", new_entry_path) %>

<% end%>

app/views/entries/new.html.erb
<%= form_for(Entry.new) do |form| %>
<p><%= form.label("title") %></p>
<p><%= form.text_field("title") %></p>
<p><%= form.label("contents") %></p>
<p><%= form.text_area("contents") %></p>
<p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/show.html.erb
<h2><%= @entry.title %></h2>
<p><%= @entry.date%></p>
<p><%= @entry.contents%></p>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diary</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
resources "entries"
<p>Find me in app/views/welcome/index.html.erb</p>
	<div>
		<h1>My favorite websites</h1>
	
		<%for url, name in @websites %>
		<li><a href="<%= url %>"><%= name %></a></li>
		<% end %>
		</div>
		<img src="http://railsgirls.com/images/rg-warsaw.png" />

	<h1>My Diary</h1>
	<% for entry in @entries %>
	<h2><%= entry.title %></h2>
	<p><%=entry.date %></p>
	<p><%= entry.contents %></p>
	<%% end %>

	<div>
		<h2>Submitted a Rails Girls application</h2>
		<p>1.02.2014</p>
		<p>Barbeque pork buns are my fav!</p>
		<h2>Really don't need to eat anyhing else</h2>
		<p>15.02.2014</p>
		<p>Received an email that my application got accepted! I'll be at an RG workshop next week!</p>
		<h2>The first day starts....</h2>
		 <p>22.02.2014</p>
		 <p>Today is the first day of the Rails Girls workshop blah blah yada yada so so ok ok done.</p>
		</div>